server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
