server:
  port: 9011
spring:
  application:
    name: tensquare-friend
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_friend?characterEncoding=UTF8
    data-username: root
    data-password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast
    ttl: 360000
