server:
  port: 9012
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-manager: #key值
      path: /user/**
      serviceId: tensquare-user #指定Eureka注册中心中的服务id
jwt:
  config:
    key: itcast

